var firstname="Ilakkiya";
var lastname="Lakshmanan";
var maritalstatus="married";
var country="India";
var age=25;
console.log(firstname);
console.log(lastname);
console.log(maritalstatus);
console.log(country);
console.log(age);
